"use client";
import type { Plan, PlanSection } from "@/types/plan";

export const plansSpanish: Plan[] = [
  {
    id: "plan-despegue",
    name: "Plan Despegue",
    price: 3840,
    image: "/images/plans/plan-despegue.jpg",
    intro: "",
    features: [
      "Investigación básica de marca y producto",
      "Desarrollo de **1 concepto creativo**",
      "Documento de concepto (1–2 páginas)",
      "Entrega digital",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-1-desarrollo-de-concepto-creativo-virtual",
    groupTitle: "Desarrollo de concepto creativo (virtual)",
    groupLabel: "SECCIÓN 1: Desarrollo de concepto creativo (virtual)",
  },
  {
    id: "plan-impacto",
    name: "Plan Impacto",
    price: 5950,
    image: "/images/plans/plan-impacto.jpg",
    intro: "",
    features: [
      "Análisis de marca y público objetivo",
      "Desarrollo de **2 propuestas de concepto creativo**",
      "Documento creativo detallado",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-1-desarrollo-de-concepto-creativo-virtual",
    groupTitle: "Desarrollo de concepto creativo (virtual)",
    groupLabel: "SECCIÓN 1: Desarrollo de concepto creativo (virtual)",
  },
  {
    id: "plan-titan",
    name: "Plan Titan",
    price: 10740,
    image: "/images/plans/plan-titan.jpg",
    intro: "",
    features: [
      "Investigación de mercado básica",
      "Desarrollo de **2 conceptos creativos publicitarios**",
      "Documento creativo completo",
      "Recomendación de estilo audiovisual",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-1-desarrollo-de-concepto-creativo-virtual",
    groupTitle: "Desarrollo de concepto creativo (virtual)",
    groupLabel: "SECCIÓN 1: Desarrollo de concepto creativo (virtual)",
  },
  {
    id: "plan-cumbre",
    name: "Plan Cumbre",
    price: 2280,
    image: "/images/plans/plan-cumbre.jpg",
    intro: "",
    features: [
      "Guion publicitario para video corto",
      "Duración aproximada: 30 segundos",
      "Estructura narrativa básica",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-2-guion-publicitario",
    groupTitle: "Guion publicitario",
    groupLabel: "SECCIÓN 2: Guion publicitario",
  },
  {
    id: "plan-imperio",
    name: "Plan Imperio",
    price: 8550,
    image: "/images/plans/plan-imperio.jpg",
    intro: "",
    features: [
      "Guion publicitario avanzado",
      "Duración: hasta 60 segundos",
      "Storytelling persuasivo",
      "Adaptación para anuncios digitales",
      "2 revisiones",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-2-guion-publicitario",
    groupTitle: "Guion publicitario",
    groupLabel: "SECCIÓN 2: Guion publicitario",
  },
  {
    id: "plan-titan-2",
    name: "Plan Titan",
    price: 6830,
    image: "/images/plans/plan-titan-2.jpg",
    intro: "",
    features: [
      "Guion publicitario profesional",
      "Duración: hasta 60 segundos",
      "Estructura narrativa optimizada para marketing",
      "2 revisiones",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-2-guion-publicitario",
    groupTitle: "Guion publicitario",
    groupLabel: "SECCIÓN 2: Guion publicitario",
  },
  {
    id: "plan-aurora",
    name: "Plan Aurora",
    price: 7800,
    image: "/images/plans/plan-aurora.jpg",
    intro: "",
    features: [
      "Storyboard digital detallado",
      "6 cuadros ilustrados",
      "Indicaciones de cámara y movimiento",
      "Documento visual para producción",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-4-storyboard-digital",
    groupTitle: "Storyboard digital",
    groupLabel: "SECCIÓN 4: Storyboard digital",
  },
  {
    id: "plan-destello",
    name: "Plan Destello",
    price: 4870,
    image: "/images/plans/plan-destello.jpg",
    intro: "",
    features: [
      "Storyboard digital básico",
      "3 cuadros ilustrados",
      "Descripción de escenas",
      "Entrega en PDF",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-4-storyboard-digital",
    groupTitle: "Storyboard digital",
    groupLabel: "SECCIÓN 4: Storyboard digital",
  },
  {
    id: "plan-eclipse",
    name: "Plan Eclipse",
    price: 9960,
    image: "/images/plans/plan-eclipse.jpg",
    intro: "",
    features: [
      "Storyboard profesional completo",
      "10 cuadros ilustrados",
      "Descripción técnica de escenas",
      "Flujo narrativo visual completo",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-4-storyboard-digital",
    groupTitle: "Storyboard digital",
    groupLabel: "SECCIÓN 4: Storyboard digital",
  },
  {
    id: "plan-genesis",
    name: "Plan Génesis",
    price: 9750,
    image: "/images/plans/plan-genesis.jpg",
    intro: "",
    features: [
      "1 sesión de dirección creativa remota (2 horas)",
      "Supervisión completa del proceso creativo",
      "Asesoría en estilo visual y narrativa",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-5-direccion-creativa-remota",
    groupTitle: "Dirección creativa remota",
    groupLabel: "SECCIÓN 5: Dirección creativa remota",
  },
  {
    id: "plan-idea",
    name: "Plan Idea",
    price: 3460,
    image: "/images/plans/plan-idea.jpg",
    intro: "",
    features: [
      "1 sesión virtual de dirección creativa (1 hora)",
      "Revisión de concepto o guion",
      "Recomendaciones creativas",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-5-direccion-creativa-remota",
    groupTitle: "Dirección creativa remota",
    groupLabel: "SECCIÓN 5: Dirección creativa remota",
  },
  {
    id: "plan-prisma",
    name: "Plan Prisma",
    price: 5550,
    image: "/images/plans/plan-prisma.jpg",
    intro: "",
    features: [
      "1 sesión virtual de dirección creativa (1 hora y media)",
      "Supervisión del desarrollo creativo",
      "Feedback estratégico",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-5-direccion-creativa-remota",
    groupTitle: "Dirección creativa remota",
    groupLabel: "SECCIÓN 5: Dirección creativa remota",
  },
  {
    id: "plan-chispa",
    name: "Plan Chispa",
    price: 4580,
    image: "/images/plans/plan-chispa.png",
    intro: "",
    features: [
      "Definición de objetivo de campaña",
      "Estrategia básica de contenido",
      "Recomendación de formatos",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-6-planeacion-estrategica-de-campana",
    groupTitle: "Planeación estratégica de campaña",
    groupLabel: "SECCIÓN 6: Planeación estratégica de campaña",
  },
  {
    id: "plan-trueno",
    name: "Plan Trueno",
    price: 17900,
    image: "/images/plans/plan-trueno.jpg",
    intro: "",
    features: [
      "Estrategia integral de campaña digital",
      "Planeación de contenido audiovisual",
      "Definición de formatos para anuncios",
      "Calendario estratégico de contenido",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-6-planeacion-estrategica-de-campana",
    groupTitle: "Planeación estratégica de campaña",
    groupLabel: "SECCIÓN 6: Planeación estratégica de campaña",
  },
  {
    id: "plan-voltaje",
    name: "Plan Voltaje",
    price: 11500,
    image: "/images/plans/plan-voltaje.jpg",
    intro: "",
    features: [
      "Estrategia completa de campaña",
      "Definición de público objetivo",
      "Plan de contenido audiovisual",
      "Recomendación de plataformas",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "PREPRODUCCIÓN DIGITAL",
    groupId: "seccion-6-planeacion-estrategica-de-campana",
    groupTitle: "Planeación estratégica de campaña",
    groupLabel: "SECCIÓN 6: Planeación estratégica de campaña",
  },
  {
    id: "plan-estudio",
    name: "Plan Estudio",
    price: 9800,
    image: "/images/plans/plan-estudio.jpg",
    intro: "Edición optimizada para marketing digital.",
    features: [
      "Edición de video hasta 2 minutos",
      "Transiciones profesionales",
      "Corrección básica de color",
      "Inserción de textos o títulos",
      "1 rondas de cambios",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
    groupTitle: "Edición de Videos Enviados por el Cliente",
    groupLabel: "SECCIÓN 1: Edición de Videos Enviados por el Cliente",
  },
  {
    id: "plan-produccion",
    name: "Plan Producción",
    price: 12300,
    image: "/images/plans/plan-produccion.jpg",
    intro: "Edición avanzada para contenido comercial.",
    features: [
      "Edición hasta 3 minutos",
      "Corrección de color profesional",
      "Motion graphics básicos",
      "Diseño sonoro y música licenciada",
      "2 rondas de cambios",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
    groupTitle: "Edición de Videos Enviados por el Cliente",
    groupLabel: "SECCIÓN 1: Edición de Videos Enviados por el Cliente",
  },
  {
    id: "plan-start",
    name: "Plan Start",
    price: 6800,
    image: "/images/plans/plan-start.jpg",
    intro: "Edición sencilla para contenido digital.",
    features: [
      "Edición de video hasta 60 segundos",
      "Corte y ensamblaje de clips",
      "Ajuste básico de audio",
      "Música libre de derechos básica",
      "1 ronda de cambios",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
    groupTitle: "Edición de Videos Enviados por el Cliente",
    groupLabel: "SECCIÓN 1: Edición de Videos Enviados por el Cliente",
  },
  {
    id: "cinemaster",
    name: "Cinemaster",
    price: 12990,
    image: "/images/plans/cinemaster.jpg",
    intro: "",
    features: [
      "Video hasta 90 segundos",
      "Clips de stock premium",
      "Motion graphics básicos",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-2-produccion-de-videos-con-material-de-stock",
    groupTitle: "Producción de Videos con Material de Stock",
    groupLabel: "SECCIÓN 2: Producción de Videos con Material de Stock",
  },
  {
    id: "plano",
    name: "Plano",
    price: 3890,
    image: "/images/plans/plano.jpg",
    intro: "",
    features: [
      "Video hasta 30 segundos",
      "Clips de stock estándar",
      "Edición básica",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-2-produccion-de-videos-con-material-de-stock",
    groupTitle: "Producción de Videos con Material de Stock",
    groupLabel: "SECCIÓN 2: Producción de Videos con Material de Stock",
  },
  {
    id: "secuencia",
    name: "Secuencia",
    price: 8560,
    image: "/images/plans/secuencia.jpg",
    intro: "",
    features: [
      "Video hasta 60 segundos",
      "Clips de stock premium",
      "Edición profesional",
      "Textos animados",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-2-produccion-de-videos-con-material-de-stock",
    groupTitle: "Producción de Videos con Material de Stock",
    groupLabel: "SECCIÓN 2: Producción de Videos con Material de Stock",
  },
  {
    id: "plan-capture",
    name: "Plan Capture",
    price: 6770,
    image: "/images/plans/plan-capture.jpg",
    intro: "",
    features: [
      "Video animado hasta 30 segundos",
      "Animación simple de iconos y textos",
      "Música libre de derechos",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-3-creacion-de-videos-animados-corporativos",
    groupTitle: "Creación de Videos Animados Corporativos",
    groupLabel: "SECCIÓN 3: Creación de Videos Animados Corporativos",
  },
  {
    id: "plan-cinematic",
    name: "Plan Cinematic",
    price: 19500,
    image: "/images/plans/plan-cinematic.jpg",
    intro: "",
    features: [
      "Video animado hasta 90 segundos",
      "Animación avanzada",
      "Diseño visual corporativo completo",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-3-creacion-de-videos-animados-corporativos",
    groupTitle: "Creación de Videos Animados Corporativos",
    groupLabel: "SECCIÓN 3: Creación de Videos Animados Corporativos",
  },
  {
    id: "plan-motion",
    name: "Plan Motion",
    price: 12800,
    image: "/images/plans/plan-motion.jpg",
    intro: "",
    features: [
      "Video animado hasta 60 segundos",
      "Animación 2D corporativa",
      "Diseño gráfico personalizado",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-3-creacion-de-videos-animados-corporativos",
    groupTitle: "Creación de Videos Animados Corporativos",
    groupLabel: "SECCIÓN 3: Creación de Videos Animados Corporativos",
  },
  {
    id: "plan-espectaculo",
    name: "Plan Espectáculo",
    price: 11650,
    image: "/images/plans/plan-espectaculo.jpg",
    intro: "",
    features: [
      "Animación publicitaria avanzada",
      "Hasta 60 segundos",
      "Integración con video o gráficos",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-4-motion-graphics-publicitarios",
    groupTitle: "Motion Graphics Publicitarios",
    groupLabel: "SECCIÓN 4: Motion Graphics Publicitarios",
  },
  {
    id: "plan-flash",
    name: "Plan Flash",
    price: 1720,
    image: "/images/plans/plan-flash.jpg",
    intro: "",
    features: [
      "Animación simple de textos o logotipos",
      "Duración hasta 15 segundos",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-4-motion-graphics-publicitarios",
    groupTitle: "Motion Graphics Publicitarios",
    groupLabel: "SECCIÓN 4: Motion Graphics Publicitarios",
  },
  {
    id: "plan-impacto-2",
    name: "Plan Impacto",
    price: 4210,
    image: "/images/plans/plan-impacto-2.jpg",
    intro: "",
    features: [
      "Motion graphics publicitarios",
      "Animación hasta 30 segundos",
      "Diseño visual personalizado",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-4-motion-graphics-publicitarios",
    groupTitle: "Motion Graphics Publicitarios",
    groupLabel: "SECCIÓN 4: Motion Graphics Publicitarios",
  },
  {
    id: "plan-concepto",
    name: "Plan Concepto",
    price: 15880,
    image: "/images/plans/plan-concepto.jpg",
    intro: "",
    features: [
      "Video explicativo hasta 60 segundos",
      "Animación 2D profesional",
      "Guion visual estructurado",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-5-videos-explicativos-animados-explainer-videos",
    groupTitle: "Videos Explicativos Animados (Explainer Videos)",
    groupLabel: "SECCIÓN 5: Videos Explicativos Animados (Explainer Videos)",
  },
  {
    id: "plan-idea-2",
    name: "Plan Idea",
    price: 8960,
    image: "/images/plans/plan-idea-2.jpg",
    intro: "",
    features: [
      "Video explicativo hasta 45 segundos",
      "Animación simple",
      "Música básica",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-5-videos-explicativos-animados-explainer-videos",
    groupTitle: "Videos Explicativos Animados (Explainer Videos)",
    groupLabel: "SECCIÓN 5: Videos Explicativos Animados (Explainer Videos)",
  },
  {
    id: "plan-obra-maestra",
    name: "Plan Obra Maestra",
    price: 24950,
    image: "/images/plans/plan-obra-maestra.jpg",
    intro: "",
    features: [
      "Video explicativo hasta 90 segundos",
      "Animación avanzada",
      "Narrativa visual completa",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-5-videos-explicativos-animados-explainer-videos",
    groupTitle: "Videos Explicativos Animados (Explainer Videos)",
    groupLabel: "SECCIÓN 5: Videos Explicativos Animados (Explainer Videos)",
  },
  {
    id: "plan-elite",
    name: "Plan Elite",
    price: 3980,
    image: "/images/plans/plan-elite.jpg",
    intro: "",
    features: [
      "Edición de 2 reels",
      "Subtítulos dinámicos",
      "Transiciones modernas",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-6-edicion-de-reels-para-redes-sociales",
    groupTitle: "Edición de Reels para Redes Sociales",
    groupLabel: "SECCIÓN 6: Edición de Reels para Redes Sociales",
  },
  {
    id: "plan-select",
    name: "Plan Select",
    price: 2350,
    image: "/images/plans/plan-select.jpg",
    intro: "",
    features: [
      "Edición de 1 reel",
      "Duración hasta 30 segundos",
      "Subtítulos simples",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-6-edicion-de-reels-para-redes-sociales",
    groupTitle: "Edición de Reels para Redes Sociales",
    groupLabel: "SECCIÓN 6: Edición de Reels para Redes Sociales",
  },
  {
    id: "plan-signature-film",
    name: "Plan Signature Film",
    price: 6960,
    image: "/images/plans/plan-signature-film.jpg",
    intro: "",
    features: [
      "Edición de 3 reels",
      "Edición dinámica avanzada",
      "Subtítulos animados",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-6-edicion-de-reels-para-redes-sociales",
    groupTitle: "Edición de Reels para Redes Sociales",
    groupLabel: "SECCIÓN 6: Edición de Reels para Redes Sociales",
  },
  {
    id: "basic",
    name: "Basic",
    price: 4210,
    image: "/images/plans/basic.jpg",
    intro: "",
    features: [
      "Video promocional hasta 45 segundos",
      "Edición básica",
      "Música libre de derechos",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
    groupTitle: "Videos Promocionales para Servicios o Modelaje",
    groupLabel: "SECCIÓN 7 : Videos Promocionales para Servicios o Modelaje",
  },
  {
    id: "premium",
    name: "Premium",
    price: 12740,
    image: "/images/plans/premium.jpg",
    intro: "",
    features: [
      "Video promocional hasta 2 minutos",
      "Edición cinematográfica",
      "Motion graphics promocionales",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
    groupTitle: "Videos Promocionales para Servicios o Modelaje",
    groupLabel: "SECCIÓN 7 : Videos Promocionales para Servicios o Modelaje",
  },
  {
    id: "pro",
    name: "Pro",
    price: 7820,
    image: "/images/plans/pro.jpg",
    intro: "",
    features: [
      "Video promocional hasta 90 segundos",
      "Corrección de color",
      "Textos promocionales",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groupId: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
    groupTitle: "Videos Promocionales para Servicios o Modelaje",
    groupLabel: "SECCIÓN 7 : Videos Promocionales para Servicios o Modelaje",
  },
  {
    id: "base",
    name: "Base",
    price: 2950,
    image: "/images/plans/base.jpg",
    intro: "Corrección básica para contenido digital.",
    features: [
      "Ajuste de brillo, contraste y saturación",
      "Balance de color general",
      "Video hasta 60 segundos",
      "1 revisión",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "correccion-de-color",
    groupTitle: "Corrección de Color",
    groupLabel: "Corrección de Color",
  },
  {
    id: "master",
    name: "Master",
    price: 17920,
    image: "/images/plans/master.jpg",
    intro: "Corrección de color avanzada para proyectos comerciales.",
    features: [
      "Color grading cinematográfico",
      "Look visual personalizado",
      "Ajustes escena por escena",
      "Video hasta 3 minutos",
      "2 revisiones",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "correccion-de-color",
    groupTitle: "Corrección de Color",
    groupLabel: "Corrección de Color",
  },
  {
    id: "plus",
    name: "Plus",
    price: 5280,
    image: "/images/plans/plus.jpg",
    intro: "Corrección de color optimizada para publicidad y redes sociales.",
    features: [
      "Color grading profesional",
      "Ajuste de tonos de piel",
      "Estilo visual cinematográfico",
      "Video hasta 60 segundos",
      "2 revisiones",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "correccion-de-color",
    groupTitle: "Corrección de Color",
    groupLabel: "Corrección de Color",
  },
  {
    id: "basico",
    name: "Básico",
    price: 1880,
    image: "/images/plans/basico.jpg",
    intro: "",
    features: [
      "3 transiciones animadas",
      "Animación simple de textos",
      "Integración en video existente",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Diseño de Animaciones y Transiciones",
    groupLabel: "Diseño de Animaciones y Transiciones",
  },
  {
    id: "express",
    name: "Express",
    price: 480,
    image: "/images/plans/express.png",
    intro: "",
    features: [
      "1 transición animada básica",
      "Animación simple de un texto o título",
      "Adaptación para un video de hasta 15 segundos",
      "Entrega en formato digital",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Diseño de Animaciones y Transiciones",
    groupLabel: "Diseño de Animaciones y Transiciones",
  },
  {
    id: "premium-2",
    name: "Premium",
    price: 10690,
    image: "/images/plans/premium-2.jpg",
    intro: "",
    features: [
      "10 animaciones o transiciones personalizadas",
      "Motion graphics avanzados",
      "Integración completa en video",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Diseño de Animaciones y Transiciones",
    groupLabel: "Diseño de Animaciones y Transiciones",
  },
  {
    id: "profesional",
    name: "Profesional",
    price: 3270,
    image: "/images/plans/profesional.jpg",
    intro: "",
    features: [
      "6 transiciones animadas",
      "Animación de títulos",
      "Estilo visual personalizado",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Diseño de Animaciones y Transiciones",
    groupLabel: "Diseño de Animaciones y Transiciones",
  },
  {
    id: "starter",
    name: "Starter",
    price: 910,
    image: "/images/plans/starter.png",
    intro: "",
    features: [
      "2 transiciones animadas",
      "Animación de hasta 2 textos o títulos",
      "Integración en video existente de hasta 30 segundos",
      "Ajuste de tiempos y movimientos básicos",
      "1 ronda de cambios menores",
      "Entrega en formato digital",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Diseño de Animaciones y Transiciones",
    groupLabel: "Diseño de Animaciones y Transiciones",
  },
  {
    id: "plan-basico",
    name: "Plan Básico",
    price: 2820,
    image: "/images/plans/plan-basico.jpg",
    intro: "",
    features: [
      "Intro animada con logo",
      "Duración hasta 5 segundos",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-intros-outros-corporativas",
    groupTitle: "Diseño de Intros / Outros Corporativas",
    groupLabel: "Diseño de Intros / Outros Corporativas",
  },
  {
    id: "plan-premium",
    name: "Plan Premium",
    price: 12990,
    image: "/images/plans/plan-premium.jpg",
    intro: "",
    features: [
      "Intro y outro corporativa personalizada",
      "Motion graphics avanzados",
      "Identidad visual animada",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-intros-outros-corporativas",
    groupTitle: "Diseño de Intros / Outros Corporativas",
    groupLabel: "Diseño de Intros / Outros Corporativas",
  },
  {
    id: "plan-profesional",
    name: "Plan Profesional",
    price: 5860,
    image: "/images/plans/plan-profesional.jpg",
    intro: "",
    features: [
      "Intro y outro animadas",
      "Animación de logo y textos",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groupId: "diseno-de-intros-outros-corporativas",
    groupTitle: "Diseño de Intros / Outros Corporativas",
    groupLabel: "Diseño de Intros / Outros Corporativas",
  },
];

export const planSectionsSpanish: PlanSection[] = [
  {
    id: "preproduccion-digital",
    title: "PREPRODUCCIÓN DIGITAL",
    groups: [
      {
        id: "seccion-1-desarrollo-de-concepto-creativo-virtual",
        title: "Desarrollo de concepto creativo (virtual)",
        label: "SECCIÓN 1: Desarrollo de concepto creativo (virtual)",
        planIds: [
          "plan-despegue",
          "plan-impacto",
          "plan-titan",
        ],
      },
      {
        id: "seccion-2-guion-publicitario",
        title: "Guion publicitario",
        label: "SECCIÓN 2: Guion publicitario",
        planIds: [
          "plan-cumbre",
          "plan-imperio",
          "plan-titan-2",
        ],
      },
      {
        id: "seccion-4-storyboard-digital",
        title: "Storyboard digital",
        label: "SECCIÓN 4: Storyboard digital",
        planIds: [
          "plan-aurora",
          "plan-destello",
          "plan-eclipse",
        ],
      },
      {
        id: "seccion-5-direccion-creativa-remota",
        title: "Dirección creativa remota",
        label: "SECCIÓN 5: Dirección creativa remota",
        planIds: [
          "plan-genesis",
          "plan-idea",
          "plan-prisma",
        ],
      },
      {
        id: "seccion-6-planeacion-estrategica-de-campana",
        title: "Planeación estratégica de campaña",
        label: "SECCIÓN 6: Planeación estratégica de campaña",
        planIds: [
          "plan-chispa",
          "plan-trueno",
          "plan-voltaje",
        ],
      },
    ],
  },
  {
    id: "produccion-audiovisual-remota",
    title: "PRODUCCIÓN AUDIOVISUAL REMOTA",
    groups: [
      {
        id: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
        title: "Edición de Videos Enviados por el Cliente",
        label: "SECCIÓN 1: Edición de Videos Enviados por el Cliente",
        planIds: [
          "plan-estudio",
          "plan-produccion",
          "plan-start",
        ],
      },
      {
        id: "seccion-2-produccion-de-videos-con-material-de-stock",
        title: "Producción de Videos con Material de Stock",
        label: "SECCIÓN 2: Producción de Videos con Material de Stock",
        planIds: [
          "cinemaster",
          "plano",
          "secuencia",
        ],
      },
      {
        id: "seccion-3-creacion-de-videos-animados-corporativos",
        title: "Creación de Videos Animados Corporativos",
        label: "SECCIÓN 3: Creación de Videos Animados Corporativos",
        planIds: [
          "plan-capture",
          "plan-cinematic",
          "plan-motion",
        ],
      },
      {
        id: "seccion-4-motion-graphics-publicitarios",
        title: "Motion Graphics Publicitarios",
        label: "SECCIÓN 4: Motion Graphics Publicitarios",
        planIds: [
          "plan-espectaculo",
          "plan-flash",
          "plan-impacto-2",
        ],
      },
      {
        id: "seccion-5-videos-explicativos-animados-explainer-videos",
        title: "Videos Explicativos Animados (Explainer Videos)",
        label: "SECCIÓN 5: Videos Explicativos Animados (Explainer Videos)",
        planIds: [
          "plan-concepto",
          "plan-idea-2",
          "plan-obra-maestra",
        ],
      },
      {
        id: "seccion-6-edicion-de-reels-para-redes-sociales",
        title: "Edición de Reels para Redes Sociales",
        label: "SECCIÓN 6: Edición de Reels para Redes Sociales",
        planIds: [
          "plan-elite",
          "plan-select",
          "plan-signature-film",
        ],
      },
      {
        id: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
        title: "Videos Promocionales para Servicios o Modelaje",
        label: "SECCIÓN 7 : Videos Promocionales para Servicios o Modelaje",
        planIds: [
          "basic",
          "premium",
          "pro",
        ],
      },
    ],
  },
  {
    id: "postproduccion-audiovisual-digital",
    title: "POSTPRODUCCIÓN AUDIOVISUAL DIGITAL",
    groups: [
      {
        id: "correccion-de-color",
        title: "Corrección de Color",
        label: "Corrección de Color",
        planIds: [
          "base",
          "master",
          "plus",
        ],
      },
      {
        id: "diseno-de-animaciones-y-transiciones",
        title: "Diseño de Animaciones y Transiciones",
        label: "Diseño de Animaciones y Transiciones",
        planIds: [
          "basico",
          "express",
          "premium-2",
          "profesional",
          "starter",
        ],
      },
      {
        id: "diseno-de-intros-outros-corporativas",
        title: "Diseño de Intros / Outros Corporativas",
        label: "Diseño de Intros / Outros Corporativas",
        planIds: [
          "plan-basico",
          "plan-premium",
          "plan-profesional",
        ],
      },
    ],
  },
];

export const plansEnglish: Plan[] = [
  {
    id: "plan-despegue",
    name: "Takeoff Plan",
    price: 3840,
    image: "/images/plans/plan-despegue.jpg",
    intro: "",
    features: [
      "Basic brand and product research",
      "Development of **1 creative concept**",
      "Concept document (1–2 pages)",
      "Digital delivery",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-1-desarrollo-de-concepto-creativo-virtual",
    groupTitle: "Creative concept development (virtual)",
    groupLabel: "SECTION 1: Creative concept development (virtual)",
  },
  {
    id: "plan-impacto",
    name: "Impact Plan",
    price: 5950,
    image: "/images/plans/plan-impacto.jpg",
    intro: "",
    features: [
      "Brand and target audience analysis",
      "Development of **2 creative concept proposals**",
      "Detailed creative document",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-1-desarrollo-de-concepto-creativo-virtual",
    groupTitle: "Creative concept development (virtual)",
    groupLabel: "SECTION 1: Creative concept development (virtual)",
  },
  {
    id: "plan-titan",
    name: "Titan Plan",
    price: 10740,
    image: "/images/plans/plan-titan.jpg",
    intro: "",
    features: [
      "Basic market research",
      "Development of **2 advertising creative concepts**",
      "Complete creative document",
      "Audiovisual style recommendation",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-1-desarrollo-de-concepto-creativo-virtual",
    groupTitle: "Creative concept development (virtual)",
    groupLabel: "SECTION 1: Creative concept development (virtual)",
  },
  {
    id: "plan-cumbre",
    name: "Summit Plan",
    price: 2280,
    image: "/images/plans/plan-cumbre.jpg",
    intro: "",
    features: [
      "Advertising script for short video",
      "Approximate duration: 30 seconds",
      "Basic narrative structure",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-2-guion-publicitario",
    groupTitle: "Advertising script",
    groupLabel: "SECTION 2: Advertising script",
  },
  {
    id: "plan-imperio",
    name: "Empire Plan",
    price: 8550,
    image: "/images/plans/plan-imperio.jpg",
    intro: "",
    features: [
      "Advanced advertising script",
      "Duration: up to 60 seconds",
      "Persuasive storytelling",
      "Adaptation for digital ads",
      "2 revisions",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-2-guion-publicitario",
    groupTitle: "Advertising script",
    groupLabel: "SECTION 2: Advertising script",
  },
  {
    id: "plan-titan-2",
    name: "Titan Plan",
    price: 6830,
    image: "/images/plans/plan-titan-2.jpg",
    intro: "",
    features: [
      "Professional advertising script",
      "Duration: up to 60 seconds",
      "Narrative structure optimized for marketing",
      "2 revisions",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-2-guion-publicitario",
    groupTitle: "Advertising script",
    groupLabel: "SECTION 2: Advertising script",
  },
  {
    id: "plan-aurora",
    name: "Aurora Plan",
    price: 7800,
    image: "/images/plans/plan-aurora.jpg",
    intro: "",
    features: [
      "Detailed digital storyboard",
      "6 illustrated frames",
      "Camera and movement directions",
      "Visual document for production",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-4-storyboard-digital",
    groupTitle: "Digital storyboard",
    groupLabel: "SECTION 4: Digital storyboard",
  },
  {
    id: "plan-destello",
    name: "Sparkle Plan",
    price: 4870,
    image: "/images/plans/plan-destello.jpg",
    intro: "",
    features: [
      "Basic digital storyboard",
      "3 illustrated frames",
      "Scene descriptions",
      "PDF delivery",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-4-storyboard-digital",
    groupTitle: "Digital storyboard",
    groupLabel: "SECTION 4: Digital storyboard",
  },
  {
    id: "plan-eclipse",
    name: "Eclipse Plan",
    price: 9960,
    image: "/images/plans/plan-eclipse.jpg",
    intro: "",
    features: [
      "Complete professional storyboard",
      "10 illustrated frames",
      "Technical scene descriptions",
      "Complete visual narrative flow",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-4-storyboard-digital",
    groupTitle: "Digital storyboard",
    groupLabel: "SECTION 4: Digital storyboard",
  },
  {
    id: "plan-genesis",
    name: "Genesis Plan",
    price: 9750,
    image: "/images/plans/plan-genesis.jpg",
    intro: "",
    features: [
      "1 remote creative direction session (2 hours)",
      "Complete supervision of the creative process",
      "Visual style and narrative consulting",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-5-direccion-creativa-remota",
    groupTitle: "Remote creative direction",
    groupLabel: "SECTION 5: Remote creative direction",
  },
  {
    id: "plan-idea",
    name: "Idea Plan",
    price: 3460,
    image: "/images/plans/plan-idea.jpg",
    intro: "",
    features: [
      "1 virtual creative direction session (1 hour)",
      "Concept or script review",
      "Creative recommendations",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-5-direccion-creativa-remota",
    groupTitle: "Remote creative direction",
    groupLabel: "SECTION 5: Remote creative direction",
  },
  {
    id: "plan-prisma",
    name: "Prism Plan",
    price: 5550,
    image: "/images/plans/plan-prisma.jpg",
    intro: "",
    features: [
      "1 virtual creative direction session (1 hour and a half)",
      "Supervision of creative development",
      "Strategic feedback",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-5-direccion-creativa-remota",
    groupTitle: "Remote creative direction",
    groupLabel: "SECTION 5: Remote creative direction",
  },
  {
    id: "plan-chispa",
    name: "Spark Plan",
    price: 4580,
    image: "/images/plans/plan-chispa.png",
    intro: "",
    features: [
      "Campaign objective definition",
      "Basic content strategy",
      "Format recommendations",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-6-planeacion-estrategica-de-campana",
    groupTitle: "Strategic campaign planning",
    groupLabel: "SECTION 6: Strategic campaign planning",
  },
  {
    id: "plan-trueno",
    name: "Thunder Plan",
    price: 17900,
    image: "/images/plans/plan-trueno.jpg",
    intro: "",
    features: [
      "Comprehensive digital campaign strategy",
      "Audiovisual content planning",
      "Definition of ad formats",
      "Strategic content calendar",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-6-planeacion-estrategica-de-campana",
    groupTitle: "Strategic campaign planning",
    groupLabel: "SECTION 6: Strategic campaign planning",
  },
  {
    id: "plan-voltaje",
    name: "Voltage Plan",
    price: 11500,
    image: "/images/plans/plan-voltaje.jpg",
    intro: "",
    features: [
      "Complete campaign strategy",
      "Target audience definition",
      "Audiovisual content plan",
      "Platform recommendations",
    ],
    sectionId: "preproduccion-digital",
    sectionTitle: "DIGITAL PRE-PRODUCTION",
    groupId: "seccion-6-planeacion-estrategica-de-campana",
    groupTitle: "Strategic campaign planning",
    groupLabel: "SECTION 6: Strategic campaign planning",
  },
  {
    id: "plan-estudio",
    name: "Studio Plan",
    price: 9800,
    image: "/images/plans/plan-estudio.jpg",
    intro: "Editing optimized for digital marketing.",
    features: [
      "Video editing up to 2 minutes",
      "Professional transitions",
      "Basic color correction",
      "Text or title insertion",
      "1 round of revisions",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
    groupTitle: "Editing of Client-Submitted Videos",
    groupLabel: "SECTION 1: Editing of Client-Submitted Videos",
  },
  {
    id: "plan-produccion",
    name: "Production Plan",
    price: 12300,
    image: "/images/plans/plan-produccion.jpg",
    intro: "Advanced editing for commercial content.",
    features: [
      "Editing up to 3 minutes",
      "Professional color correction",
      "Basic motion graphics",
      "Sound design and licensed music",
      "2 rounds of revisions",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
    groupTitle: "Editing of Client-Submitted Videos",
    groupLabel: "SECTION 1: Editing of Client-Submitted Videos",
  },
  {
    id: "plan-start",
    name: "Start Plan",
    price: 6800,
    image: "/images/plans/plan-start.jpg",
    intro: "Simple editing for digital content.",
    features: [
      "Video editing up to 60 seconds",
      "Clip cutting and assembly",
      "Basic audio adjustment",
      "Basic royalty-free music",
      "1 round of revisions",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
    groupTitle: "Editing of Client-Submitted Videos",
    groupLabel: "SECTION 1: Editing of Client-Submitted Videos",
  },
  {
    id: "cinemaster",
    name: "Cinemaster",
    price: 12990,
    image: "/images/plans/cinemaster.jpg",
    intro: "",
    features: [
      "Video up to 90 seconds",
      "Premium stock clips",
      "Basic motion graphics",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-2-produccion-de-videos-con-material-de-stock",
    groupTitle: "Video Production with Stock Footage",
    groupLabel: "SECTION 2: Video Production with Stock Footage",
  },
  {
    id: "plano",
    name: "Shot",
    price: 3890,
    image: "/images/plans/plano.jpg",
    intro: "",
    features: [
      "Video up to 30 seconds",
      "Standard stock clips",
      "Basic editing",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-2-produccion-de-videos-con-material-de-stock",
    groupTitle: "Video Production with Stock Footage",
    groupLabel: "SECTION 2: Video Production with Stock Footage",
  },
  {
    id: "secuencia",
    name: "Sequence",
    price: 8560,
    image: "/images/plans/secuencia.jpg",
    intro: "",
    features: [
      "Video up to 60 seconds",
      "Premium stock clips",
      "Professional editing",
      "Animated texts",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-2-produccion-de-videos-con-material-de-stock",
    groupTitle: "Video Production with Stock Footage",
    groupLabel: "SECTION 2: Video Production with Stock Footage",
  },
  {
    id: "plan-capture",
    name: "Capture Plan",
    price: 6770,
    image: "/images/plans/plan-capture.jpg",
    intro: "",
    features: [
      "Animated video up to 30 seconds",
      "Simple animation of icons and texts",
      "Royalty-free music",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-3-creacion-de-videos-animados-corporativos",
    groupTitle: "Creation of Corporate Animated Videos",
    groupLabel: "SECTION 3: Creation of Corporate Animated Videos",
  },
  {
    id: "plan-cinematic",
    name: "Cinematic Plan",
    price: 19500,
    image: "/images/plans/plan-cinematic.jpg",
    intro: "",
    features: [
      "Animated video up to 90 seconds",
      "Advanced animation",
      "Complete corporate visual design",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-3-creacion-de-videos-animados-corporativos",
    groupTitle: "Creation of Corporate Animated Videos",
    groupLabel: "SECTION 3: Creation of Corporate Animated Videos",
  },
  {
    id: "plan-motion",
    name: "Motion Plan",
    price: 12800,
    image: "/images/plans/plan-motion.jpg",
    intro: "",
    features: [
      "Animated video up to 60 seconds",
      "2D corporate animation",
      "Custom graphic design",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-3-creacion-de-videos-animados-corporativos",
    groupTitle: "Creation of Corporate Animated Videos",
    groupLabel: "SECTION 3: Creation of Corporate Animated Videos",
  },
  {
    id: "plan-espectaculo",
    name: "Show Plan",
    price: 11650,
    image: "/images/plans/plan-espectaculo.jpg",
    intro: "",
    features: [
      "Advanced advertising animation",
      "Up to 60 seconds",
      "Integration with video or graphics",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-4-motion-graphics-publicitarios",
    groupTitle: "Advertising Motion Graphics",
    groupLabel: "SECTION 4: Advertising Motion Graphics",
  },
  {
    id: "plan-flash",
    name: "Flash Plan",
    price: 1720,
    image: "/images/plans/plan-flash.jpg",
    intro: "",
    features: [
      "Simple animation of texts or logos",
      "Duration up to 15 seconds",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-4-motion-graphics-publicitarios",
    groupTitle: "Advertising Motion Graphics",
    groupLabel: "SECTION 4: Advertising Motion Graphics",
  },
  {
    id: "plan-impacto-2",
    name: "Impact Plan",
    price: 4210,
    image: "/images/plans/plan-impacto-2.jpg",
    intro: "",
    features: [
      "Advertising motion graphics",
      "Animation up to 30 seconds",
      "Custom visual design",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-4-motion-graphics-publicitarios",
    groupTitle: "Advertising Motion Graphics",
    groupLabel: "SECTION 4: Advertising Motion Graphics",
  },
  {
    id: "plan-concepto",
    name: "Concept Plan",
    price: 15880,
    image: "/images/plans/plan-concepto.jpg",
    intro: "",
    features: [
      "Explainer video up to 60 seconds",
      "Professional 2D animation",
      "Structured visual script",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-5-videos-explicativos-animados-explainer-videos",
    groupTitle: "Animated Explainer Videos",
    groupLabel: "SECTION 5: Animated Explainer Videos",
  },
  {
    id: "plan-idea-2",
    name: "Idea Plan",
    price: 8960,
    image: "/images/plans/plan-idea-2.jpg",
    intro: "",
    features: [
      "Explainer video up to 45 seconds",
      "Simple animation",
      "Basic music",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-5-videos-explicativos-animados-explainer-videos",
    groupTitle: "Animated Explainer Videos",
    groupLabel: "SECTION 5: Animated Explainer Videos",
  },
  {
    id: "plan-obra-maestra",
    name: "Masterpiece Plan",
    price: 24950,
    image: "/images/plans/plan-obra-maestra.jpg",
    intro: "",
    features: [
      "Explainer video up to 90 seconds",
      "Advanced animation",
      "Complete visual narrative",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-5-videos-explicativos-animados-explainer-videos",
    groupTitle: "Animated Explainer Videos",
    groupLabel: "SECTION 5: Animated Explainer Videos",
  },
  {
    id: "plan-elite",
    name: "Elite Plan",
    price: 3980,
    image: "/images/plans/plan-elite.jpg",
    intro: "",
    features: [
      "Editing of 2 reels",
      "Dynamic subtitles",
      "Modern transitions",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-6-edicion-de-reels-para-redes-sociales",
    groupTitle: "Reels Editing for Social Media",
    groupLabel: "SECTION 6: Reels Editing for Social Media",
  },
  {
    id: "plan-select",
    name: "Select Plan",
    price: 2350,
    image: "/images/plans/plan-select.jpg",
    intro: "",
    features: [
      "Editing of 1 reel",
      "Duration up to 30 seconds",
      "Simple subtitles",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-6-edicion-de-reels-para-redes-sociales",
    groupTitle: "Reels Editing for Social Media",
    groupLabel: "SECTION 6: Reels Editing for Social Media",
  },
  {
    id: "plan-signature-film",
    name: "Signature Film Plan",
    price: 6960,
    image: "/images/plans/plan-signature-film.jpg",
    intro: "",
    features: [
      "Editing of 3 reels",
      "Advanced dynamic editing",
      "Animated subtitles",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-6-edicion-de-reels-para-redes-sociales",
    groupTitle: "Reels Editing for Social Media",
    groupLabel: "SECTION 6: Reels Editing for Social Media",
  },
  {
    id: "basic",
    name: "Basic",
    price: 4210,
    image: "/images/plans/basic.jpg",
    intro: "",
    features: [
      "Promotional video up to 45 seconds",
      "Basic editing",
      "Royalty-free music",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
    groupTitle: "Promotional Videos for Services or Modeling",
    groupLabel: "SECTION 7: Promotional Videos for Services or Modeling",
  },
  {
    id: "premium",
    name: "Premium",
    price: 12740,
    image: "/images/plans/premium.jpg",
    intro: "",
    features: [
      "Promotional video up to 2 minutes",
      "Cinematic editing",
      "Promotional motion graphics",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
    groupTitle: "Promotional Videos for Services or Modeling",
    groupLabel: "SECTION 7: Promotional Videos for Services or Modeling",
  },
  {
    id: "pro",
    name: "Pro",
    price: 7820,
    image: "/images/plans/pro.jpg",
    intro: "",
    features: [
      "Promotional video up to 90 seconds",
      "Color correction",
      "Promotional texts",
    ],
    sectionId: "produccion-audiovisual-remota",
    sectionTitle: "REMOTE AUDIOVISUAL PRODUCTION",
    groupId: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
    groupTitle: "Promotional Videos for Services or Modeling",
    groupLabel: "SECTION 7: Promotional Videos for Services or Modeling",
  },
  {
    id: "base",
    name: "Base",
    price: 2950,
    image: "/images/plans/base.jpg",
    intro: "Basic correction for digital content.",
    features: [
      "Brightness, contrast, and saturation adjustment",
      "General color balance",
      "Video up to 60 seconds",
      "1 revision",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "correccion-de-color",
    groupTitle: "Color Correction",
    groupLabel: "Color Correction",
  },
  {
    id: "master",
    name: "Master",
    price: 17920,
    image: "/images/plans/master.jpg",
    intro: "Advanced color correction for commercial projects.",
    features: [
      "Cinematic color grading",
      "Custom visual look",
      "Scene-by-scene adjustments",
      "Video up to 3 minutes",
      "2 revisions",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "correccion-de-color",
    groupTitle: "Color Correction",
    groupLabel: "Color Correction",
  },
  {
    id: "plus",
    name: "Plus",
    price: 5280,
    image: "/images/plans/plus.jpg",
    intro: "Color correction optimized for advertising and social media.",
    features: [
      "Professional color grading",
      "Skin tone adjustment",
      "Cinematic visual style",
      "Video up to 60 seconds",
      "2 revisions",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "correccion-de-color",
    groupTitle: "Color Correction",
    groupLabel: "Color Correction",
  },
  {
    id: "basico",
    name: "Basic",
    price: 1880,
    image: "/images/plans/basico.jpg",
    intro: "",
    features: [
      "3 animated transitions",
      "Simple text animation",
      "Integration into existing video",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Design of Animations and Transitions",
    groupLabel: "Design of Animations and Transitions",
  },
  {
    id: "express",
    name: "Express",
    price: 480,
    image: "/images/plans/express.png",
    intro: "",
    features: [
      "1 basic animated transition",
      "Simple animation of a text or title",
      "Adaptation for a video of up to 15 seconds",
      "Digital format delivery",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Design of Animations and Transitions",
    groupLabel: "Design of Animations and Transitions",
  },
  {
    id: "premium-2",
    name: "Premium",
    price: 10690,
    image: "/images/plans/premium-2.jpg",
    intro: "",
    features: [
      "10 custom animations or transitions",
      "Advanced motion graphics",
      "Complete video integration",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Design of Animations and Transitions",
    groupLabel: "Design of Animations and Transitions",
  },
  {
    id: "profesional",
    name: "Professional",
    price: 3270,
    image: "/images/plans/profesional.jpg",
    intro: "",
    features: [
      "6 animated transitions",
      "Title animation",
      "Custom visual style",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Design of Animations and Transitions",
    groupLabel: "Design of Animations and Transitions",
  },
  {
    id: "starter",
    name: "Starter",
    price: 910,
    image: "/images/plans/starter.png",
    intro: "",
    features: [
      "2 animated transitions",
      "Animation of up to 2 texts or titles",
      "Integration into existing video of up to 30 seconds",
      "Adjustment of basic timing and movements",
      "1 round of minor revisions",
      "Digital format delivery",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-animaciones-y-transiciones",
    groupTitle: "Design of Animations and Transitions",
    groupLabel: "Design of Animations and Transitions",
  },
  {
    id: "plan-basico",
    name: "Basic Plan",
    price: 2820,
    image: "/images/plans/plan-basico.jpg",
    intro: "",
    features: [
      "Animated intro with logo",
      "Duration up to 5 seconds",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-intros-outros-corporativas",
    groupTitle: "Corporate Intros / Outros Design",
    groupLabel: "Corporate Intros / Outros Design",
  },
  {
    id: "plan-premium",
    name: "Premium Plan",
    price: 12990,
    image: "/images/plans/plan-premium.jpg",
    intro: "",
    features: [
      "Custom corporate intro and outro",
      "Advanced motion graphics",
      "Animated visual identity",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-intros-outros-corporativas",
    groupTitle: "Corporate Intros / Outros Design",
    groupLabel: "Corporate Intros / Outros Design",
  },
  {
    id: "plan-profesional",
    name: "Professional Plan",
    price: 5860,
    image: "/images/plans/plan-profesional.jpg",
    intro: "",
    features: [
      "Animated intro and outro",
      "Logo and text animation",
    ],
    sectionId: "postproduccion-audiovisual-digital",
    sectionTitle: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groupId: "diseno-de-intros-outros-corporativas",
    groupTitle: "Corporate Intros / Outros Design",
    groupLabel: "Corporate Intros / Outros Design",
  },
];

export const planSectionsEnglish: PlanSection[] = [
  {
    id: "preproduccion-digital",
    title: "DIGITAL PRE-PRODUCTION",
    groups: [
      {
        id: "seccion-1-desarrollo-de-concepto-creativo-virtual",
        title: "Creative concept development (virtual)",
        label: "SECTION 1: Creative concept development (virtual)",
        planIds: [
          "plan-despegue",
          "plan-impacto",
          "plan-titan",
        ],
      },
      {
        id: "seccion-2-guion-publicitario",
        title: "Advertising script",
        label: "SECTION 2: Advertising script",
        planIds: [
          "plan-cumbre",
          "plan-imperio",
          "plan-titan-2",
        ],
      },
      {
        id: "seccion-4-storyboard-digital",
        title: "Digital storyboard",
        label: "SECTION 4: Digital storyboard",
        planIds: [
          "plan-aurora",
          "plan-destello",
          "plan-eclipse",
        ],
      },
      {
        id: "seccion-5-direccion-creativa-remota",
        title: "Remote creative direction",
        label: "SECTION 5: Remote creative direction",
        planIds: [
          "plan-genesis",
          "plan-idea",
          "plan-prisma",
        ],
      },
      {
        id: "seccion-6-planeacion-estrategica-de-campana",
        title: "Strategic campaign planning",
        label: "SECTION 6: Strategic campaign planning",
        planIds: [
          "plan-chispa",
          "plan-trueno",
          "plan-voltaje",
        ],
      },
    ],
  },
  {
    id: "produccion-audiovisual-remota",
    title: "REMOTE AUDIOVISUAL PRODUCTION",
    groups: [
      {
        id: "seccion-1-edicion-de-videos-enviados-por-el-cliente",
        title: "Editing of Client-Submitted Videos",
        label: "SECTION 1: Editing of Client-Submitted Videos",
        planIds: [
          "plan-estudio",
          "plan-produccion",
          "plan-start",
        ],
      },
      {
        id: "seccion-2-produccion-de-videos-con-material-de-stock",
        title: "Video Production with Stock Footage",
        label: "SECTION 2: Video Production with Stock Footage",
        planIds: [
          "cinemaster",
          "plano",
          "secuencia",
        ],
      },
      {
        id: "seccion-3-creacion-de-videos-animados-corporativos",
        title: "Creation of Corporate Animated Videos",
        label: "SECTION 3: Creation of Corporate Animated Videos",
        planIds: [
          "plan-capture",
          "plan-cinematic",
          "plan-motion",
        ],
      },
      {
        id: "seccion-4-motion-graphics-publicitarios",
        title: "Advertising Motion Graphics",
        label: "SECTION 4: Advertising Motion Graphics",
        planIds: [
          "plan-espectaculo",
          "plan-flash",
          "plan-impacto-2",
        ],
      },
      {
        id: "seccion-5-videos-explicativos-animados-explainer-videos",
        title: "Animated Explainer Videos",
        label: "SECTION 5: Animated Explainer Videos",
        planIds: [
          "plan-concepto",
          "plan-idea-2",
          "plan-obra-maestra",
        ],
      },
      {
        id: "seccion-6-edicion-de-reels-para-redes-sociales",
        title: "Reels Editing for Social Media",
        label: "SECTION 6: Reels Editing for Social Media",
        planIds: [
          "plan-elite",
          "plan-select",
          "plan-signature-film",
        ],
      },
      {
        id: "seccion-7-videos-promocionales-para-servicios-o-modelaje",
        title: "Promotional Videos for Services or Modeling",
        label: "SECTION 7: Promotional Videos for Services or Modeling",
        planIds: [
          "basic",
          "premium",
          "pro",
        ],
      },
    ],
  },
  {
    id: "postproduccion-audiovisual-digital",
    title: "DIGITAL AUDIOVISUAL POST-PRODUCTION",
    groups: [
      {
        id: "correccion-de-color",
        title: "Color Correction",
        label: "Color Correction",
        planIds: [
          "base",
          "master",
          "plus",
        ],
      },
      {
        id: "diseno-de-animaciones-y-transiciones",
        title: "Design of Animations and Transitions",
        label: "Design of Animations and Transitions",
        planIds: [
          "basico",
          "express",
          "premium-2",
          "profesional",
          "starter",
        ],
      },
      {
        id: "diseno-de-intros-outros-corporativas",
        title: "Corporate Intros / Outros Design",
        label: "Corporate Intros / Outros Design",
        planIds: [
          "plan-basico",
          "plan-premium",
          "plan-profesional",
        ],
      },
    ],
  },
];


const plansData = {
  plansSpanish,
  plansEnglish,
  planSectionsSpanish,
  planSectionsEnglish,
};

export default plansData;